version: '3.1'
services:
  mongo:
    image: mongo:bionic
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: madadmin
      MONGO_INITDB_ROOT_PASSWORD: 1lRvKgTJcORQKcAW
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data/mongo:/data/db

  express:
    image: giftr-api-w20
    container_name: giftr-api-w20
    depends_on:
      - mongo
    environment:
      API_JWTKEY: shu0q6pfwlh9rv9a5qfyv1bjjxc8s2
      API_PORT: 80
      NODE_ENV: 'stage'
    ports:
      - 3030:80
    command: node server.js